apiVersion: v1
kind: Pod
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: tooling
spec:
  nodeSelector:
    dedicated: master
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    value: ""
    effect: NoSchedule
  containers:
  - image: registry:2.6.2
    name: docker-registry
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: registry-data
      mountPath: /var/lib/registry
  volumes:
  - name: registry-data
    hostPath:
      path: /var/registry/
---
kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: tooling
spec:
  type: ClusterIP
  selector:
    app: docker-registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
