apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gogs
  name: gogs
  namespace: tooling
spec:
  nodeSelector:
    dedicated: master
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    value: ""
    effect: NoSchedule
  containers:
  - image: gogs/gogs:0.11.66
    name: gogs
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: gogs-data
      mountPath: /data
  volumes:
  - name: gogs-data
    hostPath:
      path: /var/gogs/
---
kind: Service
apiVersion: v1
metadata:
  name: gogs
  namespace: tooling
spec:
  type: NodePort
  selector:
    app: gogs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    nodePort: 31000
